# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Premios de Datos Abiertos de Madrid 2017"
email: "visualizar@medialab-prado.es"
description: "En colaboración con Medialab-Prado y el Laboratorio de Datos DataLab, el Ayuntamiento de Madrid lanza la segunda convocatoria de los concursos de Periodismo de Datos y Datatón Ciudad de Madrid con el objetivo de fomentar el uso de la información del sector público del Portal de Datos Abiertos"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Medialab-Prado"
organizerAlternateName: "DataLab"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "visualizar@medialab-prado.es"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://medialab-prado/"

# Head
metaKeywords: "event, datos abiertos, datatón, madrid, periodismo de datos, visualización, medialab-prado, datalab"
twitterAccount: "@datalabx"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/programa/", text: "Programa"}
 - {permalink: "/proyectos/", text: "Proyectos"}
 - {permalink: "/ponentes/", text: "Ponentes"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/equipo/", text: "Equipo"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Home Block
homeImage: "medialab_auditorio3_flickr.jpg"
# Hero Block
heroTitle: "DataMad <typeout> 2017"
eventDate: "Octubre - Diciembre, 2017"
typeoutTextValues: '"", "Madrid", "Datos abiertos", "Periodismo de datos", "Datatón"'
typeoutFallback: "Datos abiertos"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Acerca del DataMad"
aboutBlock:
 - {title: "Ponencias", image: "medialab_auditorio_flickr.jpg", text: "Representantes de organismos públicos nos hablarán de sus datos y servicios abiertos" }
 - {title: "Datatón", image: "medialab_gente_currando_flickr.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }
 - {title: "Premio Periodismo de Datos", image: "medialab_lab1_flickr.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "medialab_plantabaja2_flickr.jpg"
statisticBlock:
 - {count: "60", specialCharacter: "+", info: "asistentes", detail: "de diferentes perfiles"}
 - {count: "48", specialCharacter: "+", info: "horas", detail: "de trabajo con datos abiertos"}
 - {count: "4", specialCharacter: "+", info: "ponentes", detail: "de organismos públicos de la ciudad"}
 - {count: "2", specialCharacter: "", info: "modalidades", detail: "una para profesionales y otra para estudiantes de cualquier disciplina"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "medialab_auditorio2_flickr.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Expertos en datos abiertos"
rockstarSpeakersButtonText: "Ver todos los ponentes"

# Location Block
locationBlockTitle: "Lugar"
eventLocationName: "Medialab-Prado"
eventLocationLink: "http://medialab-prado.es"
eventStreetAddress: "Plaza de las Letras. Calle Alameda, 15 "
eventAddressLocality: "Madrid"
eventAddressLocalityRegion: "Madrid"
eventPostalCode: "28014"
eventAddressCountry: "Spain"
eventStartTime: "2017-10-20T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-10-22T20:00"
eventPlaceCoordinates: "40.41063,-3.69366"
mapCenterCoordinates: "40.41063,-3.69366"
mapMobileCenterCoordinates: "40.41063,-3.69366"

# Venue Block
venueBlockTitle: "Instalaciones"
venueBigImage: "medialab_exterior_architizer.jpg"
venueSmallImage1: "medialab_exterior2_architizer.jpg"
venueSmallImage2: "medialab_plantabaja2_flickr.jpg"
venueSmallImage3: "medialab_ropa_flickr.jpg"
venueTitle: "Medialab-Prado"
venueFeatures: ["Medialab-Prado es un laboratorio ciudadano de producción, investigación y difusión de proyectos culturales"]

# Tweets Feed Block
tweetsFeedImage: "medialab_ventana2_flickr.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "datamad17"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Colaboran"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "medialab_ventana_flickr.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscripciones"
ticketsInfo: "El fallo de los premios se dará a conocer el viernes 15 de diciembre"
ticketsOffers:
 -
  name: "Convocatoria de proyectos"
  price: "13"
  priceCurrency: "proyectos"
  ticketsNumber: ""
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  ticketContentList: ["Datos Abiertos", "Software Libre"]
  validFrom: "2017-08-25T10:00"
  validThrough: "2017-09-30T23:59"
  soldOut: true
  soldOutText: "Plazo terminado"
 -
  name: "Convocatoria de colaboradores"
  price: "60"
  priceCurrency: "colaboradores"
  ticketsNumber: "100"
  ribbon: "atento"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Todos los perfiles bienvenidos", "investigadores, artistas, curiosos..."]
  validFrom: "2017-10-09T00:00"
  validThrough: "2017-10-19T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=DataLabx", icon: "twitter"}
 - {link: "https://es-es.facebook.com/MedialabPradoMadrid", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://medialab-prado.es", text: "medialab-prado.es"}
   - {link: "http://datos.madrid.es/portal/site/egob/", text: "Portal de datos abiertos del Ayuntamiento de Madrid"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:visualizar@medialab-prado.es", text: "visualizar@medialab-prado.es"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas entradas"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Acerca de nosotros"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.41063, -3.69366"
logisticsMapMobileCenterCoordinates: "40.41063, -3.69366"
logisticsMapAutoDirections: false

# Proyectos
hackathonTitle: "Proyectos"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Proyectos seleccionados"
hackathonRows:
 - {title: "Refugiados: los animales abandonados en España", image: "hackathon-0.png", details: "Este proyecto nace de la voluntad de reducir la cantidad de ingresos de animales en refugios así como su estancia allí, sensibilizando acerca del tema del abandono y fomentado la adopción de animales abandonados. Inicialmente, el proyecto estará centrado en el caso del Ayuntamiento de Madrid, pero el objetivo futuro es tejer alianzas con otros centros municipales y refugios para trabajar juntos hacia el mismo objetivo."}
 - {title: "Mayorcetes", image: "hackathon-1.png", details: "Un app donde una persona mayor que no se atreve por no saber buscar, o por motivo de movilidad, no acude a un centro para mayores para comer, tomar su cañita, bailar y conocer amig@s"}
 - {title: "La historia de Madrid a través de sus calles", image: "hackathon-2.png", details: "Las calles y plazas son los sitios por los que transitamos, donde está nuestra casa, nuestro trabajo,el lugar al que vamos a comer o nuestro centro de salud. Es decir, los sitios en los que se desarrolla nuestra vida. Y sus nombres no son inocuos. Hay calles con nombres de personas, de lugares, de hechos históricos, de oficios, de animales.<br>Cuando las instituciones ponen nombre a las calles o plazas de nuestras ciudades hacen mucho más que una acción administrativa de identificación: rinden un homenaje a algo o a alguien. Normalmente, no hacemos demasiado caso a esos nombres y no nos detenemos a observar la importancia que tienen y que definen el carácter de la propia ciudad.<br>Si observamos un listado con los nombres de las calles y plazas de los 21 distritos de Madrid, nos llamará la atención la diferencia de número entre las dedicadas a hombres y a mujeres. También es importante saber el motivo por el que esas personas fueron merecedoras de una placa con su nombre, si pertenecían a la realeza, a la nobleza, al ejército, a la iglesia o si fueron reconocidas por sus méritos. Además del número de calles otorgadas a hombres y a mujeres, es importante saber dónde se sitúan éstas, en qué distritos y en qué barrios, ya que su relevancia histórica varía. Tampoco es lo mismo ser el nombre de una calle, que de una plaza, o de una avenida, o de las tres a la vez. O si es una vía peatonal o si sólo se pasa por ella en coche.<br>No solemos conocer la propia historia de la calle, cuándo se le dio su nombre y por qué se eligió ese nombre, si se ha cambiado a lo largo de la Historia, si tiene o no relación con el distrito al que pertenece, si supone un reconocimiento...<br><br>El proyecto parte de un archivo .csv con las calles actuales de los 21 distritos de Madrid que puede descargarse del portal de datos abiertos del ayuntamiento.<br>De manera consensuada, deberíamos poder establecer las diferentes categorías y subcategorías que existen en esas calles: personas (hombres y mujeres), animales, vegetales, lugares, hechos, obras..."}
 - {title: "Pure Madrid", image: "hackathon-2.png", details: "Una app que, apoyada en un servidor, permita a los usuarios conocer en cualquier momento el estado de la contaminación de Madrid y de las restricciones de tráfico asociadas.<br><br>El enfoque que le hemos dado a esta aplicación está centrado en la información que creemos que más le puede interesar al usuario: la restricción de tráfico que pueda aplicarse cada día, sin tener que estar preocupado por no conocer el estado actual.<br><br>La motivación que nos ha llevado a presentar este proyecto fue el caos que se organizó el año pasado al resultar que muchos ciudadanos no tenían disponible la información hasta el momento en el que encendían la radio o veían los letreros en las carreteras. Por esta razón el objetivo de esta aplicación será ayudar a los ciudadanos en la medida de lo posible a conocer los escenarios activados en cada momento."}
 - {title: "Tripscore", image: "hackathon-2.png", details: "Tripscore es una aplicación web que permite obtener recomendaciones de rutas en transporte público comparando las preferencias del usuario con datos históricos sobre la calidad del transporte. Esta aplicación se encuentra disponible en http://tripscore.eu/ y fue desarrollada durante el mes de Julio de 2017 en el evento Open Summer of Code en Bruselas (Bélgica) en el contexto del proyecto europeo OASIS.<br><br>Actualmente la aplicación contiene los datos de los trenes que circulan por todo Bélgica. Como participantes de OASIS, el Grupo de Ingeniería Ontológica (OEG) de la Universidad Politécnica de Madrid junto con el el Consorcio de Transportes de Madrid (CRTM) han ideado el plan de introducir los datos abiertos de transporte de la ciudad de Madrid para poder ofrecer este servicio a los ciudadanos.<br><br>Para ello se tendrán que recolectar y transformar los datos de la Empresa Municipal de Transport de Madrid (EMT) almacenados en el portal de datos abiertos del ayuntamiento de Madrid y los datos del portal de datos abierto del CRTM para que estos puedan ser consultados a través de Tripscore.<br><br>Public transport, open linked data, quality of experience, EMT, CRTM."}
 - {title: "Madrid On You", image: "hackathon-2.png", details: "Madrid on You es una aplicación (web) que utiliza como base varios conjuntos de datos abiertos del ayuntamiento de Madrid para ofrecer al usuario distintos planes y rutas para realizar en la ciudad de Madrid. Los datasets que se utilizan se encuadran dentro de las categorías de automovilismo, ciclismo, ocio y turismo."}
 - {title: "Aire de hoy, salud para mañana", image: "hackathon-2.png", details: "El aire de Madrid ha estado en boca de todos los madrileños en la actualidad tanto por la creciente conciencia por la ecología como por las medidas adoptadas para mejorar su calidad durante los últimos años.<br><br>Resulta trascendental para la salud de los madrileños tomar medidas a medio y largo plazo.<br><br>Nuestro objetivo es crear una plataforma web que, mediante la explotación de datos de acceso público, arroje luz a este tema entorno a 3 principales ejes:<br><br>Concienciación: Mediante analítica visual del estado actual del aire en tiempo real en cada punto de la Comunidad y mediante explicaciones gráficas de las consecuencias para la salud de cada elemento químico al rebasar los límites de seguridad recomendados.<br><br>Predicción: Mediante técnicas avanzadas de Inteligencia Artificial, la plataforma sera capaz de pronosticar los niveles de calidad del aire para las siguientes semanas o incluso meses.<br><br>Monitorización: La plataforma permitirá analizar los periodos en los que Madrid estaba sometida al protocolo de medidas adoptadas durante episodios de alta contaminación. Así, el usuario podrá comprobar si dichas medidas fueron suficientes para paliar los niveles de contaminación y mantenerlos estables."}
 - {title: "DoctorData", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}
 - {title: "La tecnología Blockchain en la admón. pública", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}
 - {title: "MADMobility", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}
 - {title: "M30, gestión inteligente del tráfico", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}
 - {title: "Turisfy", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}
 - {title: "Mobilomics", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "medialab_gentecurrando4_flickr.jpg"
judgesTitle: "Jurado"

# Hackathon Prizes Block
prizesTitle: "Premios"
prizes:
 - {title: "Segundo Premio", image: "prize-2.png", info: "1.000 €"}
 - {title: "Primer Premio", image: "prize-1.png", info: "2.500 €"}
 - {title: "Tercer Premio", image: "prize-3.png", info: "500 €"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Medialab-Prado"
hackathonLocationLink: "http://medialab-prado.es"
hackathonStreetAddress: "Plaza de las Letras. Calle Alameda,15"
hackathonAddressLocality: "Madrid"
hackathonAddressLocalityRegion: "Madrid"
hackathonPostalCode: "28014"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2017-10-20T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2017-10-22T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "40.41063, -3.69366"
hackathonMapCenterCoordinates: "40.41063,-3.69366"
hackathonMapMobileCenterCoordinates: "40.41063,-3.69366"
